### ISSUE TITLE
Request to trigger release build

### ISSUE THREAD

**Issue by jitendra62075** [hyperledger-labs/hlf-connector#8]
Hi @anandbanik , Can you please trigger a release build?

**Comment by arsulegai** [comment]
Generated image: ghcr.io/hyperledger-labs/hlf-connector:1.1.20-SNAPSHOT
Build: https://github.com/hyperledger-labs/hlf-connector/runs/5448769892?check_suite_focus=true

TODO:
* Increment the pom.xml version before any other patches go in.
* An alternative would be to automatically update the version as part of github’s release playbook.
* A further improvement can be to generate a release artefact without the SNAPSHOT tag.
